version: "3.9"
services:
  app:
    image: lgirardi/pytbak:0.1
    ports:
      - "5000:5000"
  proxy:
    image: haproxy:2.2-alpine
    ports: 
      - 80:80
    volumes:
      - ${PWD}/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
